### ISSUE TITLE
ScotlandJS && Cape Wrath Trail && Edinburgh Marathon

### ISSUE THREAD

**Issue by RichardLitt** [adventure-js/about#2]
ScotlandJS is on June 4.
The Edinburgh Marathon is on May 25th. I am running it. 

![Cape](http://www.kalapalo.com.br/wp-content/uploads/2015/10/CapeWrathTrail4.jpg)
What about we do the Cape Wrath Trail and have a JS conference at the end of it, after ScotlandJS?

**Comment by feross** [comment]
:+1: interested

**Comment by RichardLitt** [comment]
You know what we should do? 

We should walk to this, from ScotlandJS. Directly. Walk the Antonine wall to Glasgow, and then the West Highland Way north to the Cape Wrath Trail, to this. http://campgnd.com/

**Comment by despairblue** [comment]
Also interested :runner:

**Comment by RichardLitt** [comment]
Waiting to hear back from ScotlandJS about my talk. Will know more, following that.

**Comment by RichardLitt** [comment]
I didn't get in to ScotlandJS, but eventually got a ticket anyway. This year, I will have a wedding to go to on the same weekend of the marathon, so I won't be making it. Perhaps next year?

For now, closing this.
