### ISSUE TITLE
Train to Schefferville

### ISSUE THREAD

**Issue by RichardLitt** [adventure-js/about#6]
### The Plan 🚂🚋🚋🚋

![2014-08-09-img_3377custom-thumb](https://user-images.githubusercontent.com/910753/30513942-73dcb2e4-9ada-11e7-8810-23497b48876d.jpg)
_Picture taken from [this article](http://www.huffingtonpost.com/mike-arkus/now-this-heres-the-story_b_5664644.html)._

I want to go on the [Tshiuetin Rail](https://en.wikipedia.org/wiki/Tshiuetin_Rail_Transportation) from [Sept-Îles, Québec](http://wikitravel.org/en/Sept-%C3%8Eles) to [Schefferville, Quebec](https://en.wikipedia.org/wiki/Schefferville). The train is one of the few non-connected train systems in North America, and takes around 12 hours to complete the journey. 

In Schefferville, we can revel in being in one of the few communities with no road access to the outside world, but train access, much like [Whittier, Alaska](https://en.wikipedia.org/wiki/Whittier,_Alaska). There is a bar, a restaurant, a church, and a McGill outpost station. Most of the inhabitants speak Innu, which I don't know at all. We can figure that out. 

I fully expect to work the days I am there, while walking around, which will allow us to both hang out in a new place, and to get good remote work done. win win. 

The train arrives leaves on Monday and Thursday from Sept-Îles, and goes back on Tuesday and Friday, so I want to stay either during the week or over a long weekend. Getting to Sept-Îles will take some time, too, so expect the whole thing to take roughly 8 days.

### Dates

Late September, Early October. The sooner the better, as it is about to get cold. 

### Pricing

_Train:_ $175 Roundtrip

_Accommodation:_  
The cost of renting a place for the night in Schefferville is around $80 on AirBnB. However, they also have CouchSurfing there, and I want to try that, first. But I need to figure out dates. 

In Sept-Îles, there is a Youth Hostel for around $30 a night, which makes that much easier, and many couchsurfing hosts. I'm not concerned here. If we do it fast enough, we can also camp on the beach in my tent. 

_Travel to Sept-Îles_: I am planning on hitching, but may take the train from Montréal to Québec City, or take a car using [Amigo Express](https://www.amigoexpress.com) if I can find one. There is also a train from Montréal to Saguenay, which takes ten hours, which should have wifi, but it is expensive. Another alternative is to rent a car for the duration of the trip, which would cost around $200 total. 

### What about wifi?

There is no wifi on the train. I've looked into various internet solutions - the best seems to be either buying a [BGAN terminal](http://www.groundcontrol.com/Hughes_9202_BGAN.htm) for around $700, which would give us 100mbs, which should cover the two days we need it. If we split the cost, this isn't so bad.

There is wifi in both Sept-îles and in Schefferville.

### Who is invited?

Anyone! It would be great to have others on board for this. I can put you up in Montréal if you want to come here first, and we could head over together. 

Either comment here, or email me at richard at burntfen.com.

**Comment by hackergrrl** [comment]
Sounds like a magical :rainbow: journey. I *just* headed south from Toronto to New Jersey, and have plane tickets back to CA already. If things somehow don't work out for y'all this time, I'll be back on the east coast in January, and would be keen on making the expedition. :steam_locomotive:

**Comment by RichardLitt** [comment]
@noffle I'll let you know!

**Comment by reustle** [comment]
This sounds fantastic. I'm in if it ends up happening in the spring.

**Comment by RichardLitt** [comment]
@reustle Good to know! It looks like I may be able to go next week, so it may be expedited. But that doesn't mean we can't find something similar later, too. I know you've been thinking of train-hacks for a while.

**Comment by despairblue** [comment]
Damn, must have missed this :cry:

Same as @reustle, spring sound delightful.

**Comment by RichardLitt** [comment]
@despairblue Not yet! Meeting with six students from McGill tomorrow to plan a good time to go with some others. Maybe this week, maybe next. There will be other adventures, too. :)

**Comment by despairblue** [comment]
@RichardLitt Have a good trip and keep us posted!

**Comment by whyrusleeping** [comment]
pics or it didnt happen ;)

**Comment by RichardLitt** [comment]
Writeup incoming.

**Comment by RichardLitt** [comment]
Write up is taking longer than I expected. Here are some pictures to prove I was there and close this out! :D 

<img width="1908" alt="screen shot 2017-11-16 at 13 50 10" src="https://user-images.githubusercontent.com/910753/32909671-24a556ce-cad5-11e7-8fc0-59ec0370981d.png">
<img width="1902" alt="screen shot 2017-11-16 at 13 49 11" src="https://user-images.githubusercontent.com/910753/32909672-24b370ec-cad5-11e7-9d99-a1cf7e55e0b1.png">
<img width="1916" alt="screen shot 2017-11-16 at 13 46 35" src="https://user-images.githubusercontent.com/910753/32909673-24c167ec-cad5-11e7-92b6-123f3a600983.png">
<img width="1916" alt="screen shot 2017-11-16 at 13 46 35" src="https://user-images.githubusercontent.com/910753/32909715-3f1aeb40-cad5-11e7-88fd-303203569b97.JPG">

**Comment by hackergrrl** [comment]
Beautiful pics @RichardLitt. :open_hands:
